'use client';
import {useEffect,useState} from 'react';
import {internationalInningRecords,type InternationalLiveGame} from '@/lib/international-live-display';
type Feed={league:string;date:string;games:InternationalLiveGame[];status:string;stale?:boolean;error?:string;persistence?:{error?:string}};
const stamp=(value?:string|null)=>value?new Date(value).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'—';
export default function InternationalLiveStatus(){
 const [open,setOpen]=useState(false),[feeds,setFeeds]=useState<Record<string,Feed>>({}),[errors,setErrors]=useState<Record<string,string>>({});
 useEffect(()=>{
  if(!open)return;const controller=new AbortController();let busy=false;
  async function load(){if(busy||document.hidden)return;busy=true;try{await Promise.all(['CPBL','NPB','KBO'].map(async league=>{try{const r=await fetch(`/api/international-live?league=${league}`,{cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(45000)])});if(!r.ok)throw Error('比分資料更新失敗');const data=await r.json();if(data.league!==league||!Array.isArray(data.games))throw Error('比分資料格式不符');if(!controller.signal.aborted){setFeeds(old=>({...old,[league]:data}));setErrors(old=>({...old,[league]:''}));}}catch(e){if(!controller.signal.aborted)setErrors(old=>({...old,[league]:e instanceof Error?e.message:'更新失敗'}));}}));}finally{busy=false;}}
  void load();const timer=setInterval(()=>void load(),60000);return()=>{controller.abort();clearInterval(timer);};
 },[open]);
 return <section className="panel admin-section"><details onToggle={e=>setOpen(e.currentTarget.open)}><summary className="cursor-pointer p-5 text-lg font-bold">即時比賽資料與來源</summary><div className="space-y-4 px-5 pb-5"><p className="text-sm text-slate-300">展開時每 60 秒檢查。前台採用 MLB 雙欄版型；三聯盟目前接入的是逐局比分、打序與可用的當前投打資料，尚未接入完整逐打席／逐球歷程。逐局得分只作局數摘要，不會推算打者、出局數或壘包。缺少前局時，累計比分保留空值。</p>{['CPBL','NPB','KBO'].map(league=><section key={league} className="rounded-lg border border-slate-600 p-4"><h3 className="font-bold">{league} · {feeds[league]?.date||'讀取中'}</h3>{(errors[league]||feeds[league]?.error||feeds[league]?.persistence?.error)&&<p className="mt-2 text-sm text-amber-200">{errors[league]||feeds[league]?.error||feeds[league]?.persistence?.error}</p>}{feeds[league]?.games.map(game=><details key={game.key} className="mt-3 rounded-lg border border-slate-700 p-3"><summary className="cursor-pointer">{game.away.name} vs {game.home.name}</summary><dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-sm"><dt>比賽狀態</dt><dd>{game.status}{game.sourceStale||feeds[league].stale?' · 保留上次資料':''}</dd><dt>開賽時間</dt><dd>{stamp(game.startTime)}</dd><dt>資料來源</dt><dd>{game.source.provider}</dd><dt>最後擷取</dt><dd>{stamp(game.source.fetchedAt)}</dd><dt>局數摘要</dt><dd>{internationalInningRecords(game).length} 筆</dd><dt>當前投打</dt><dd>投手：{game.currentPitcher?.name||'未提供'}／打者：{game.currentBatter?.name||'未提供'}</dd><dt>來源備註</dt><dd className="break-all">{game.warnings?.join('、')||'—'}</dd></dl></details>)}</section>)}</div></details></section>;
}
