import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseCoversOdds,matchCoversOdds} from '../lib/covers-odds';
function page(){return '<input id="oddsScopeChangeField" value="1">Last updated Sep 10, 2026, 7:13 AM ET'+['moneyline','spread','total'].map(m=>`<table id="${m}-table"><tr class="oddsGameRow"><td><div class="td-cell game-time"><span>Today,&nbsp;</span><span>16:10</span><div class="pitcher-label">Starting Pitcher</div></div><a href="/mlb/matchup/123"><strong>TEX</strong><strong>SEA</strong></a><div class="div-cell opening-lines-div"><span class="American __american">${m==='total'?'o 7.0':'+1.5'}</span><span class="American __american">${m==='total'?'u 7.0':'-1.5'}</span></div></td><td data-book="bet365" data-game="123" data-type="spread">${['away','home'].map((s,i)=>`<div class="td-cell ${s}-cell"><a class="odds-cta ${m==='moneyline'?'moneyline':''}">${m==='moneyline'?'':m==='total'?(i?'u':'o')+' 6.5':i?'-1.5':'+1.5'}<span class="American __american">${i?'+100':'-120'}</span></a></div>`).join('')}</td></tr></table>`).join('');}
const now=Date.parse('2026-09-10T11:14:00Z');
const game:any={state:'Preview',date:'2026-09-10T20:10:00Z',away:{id:140},home:{id:136}};
test('table identity separates mislabelled source cells; prices and opening lines stay distinct',()=>{const s=parseCoversOdds(page(),now);assert.equal(s.games[0].markets.length,3);const total=s.games[0].markets[2];assert.equal(total.first.line,6.5);assert.equal(total.firstSide,'over');assert.equal(total.opening.first,'o 7.0');assert.equal(total.first.decimal,1+100/120);assert.equal(s.sourceUpdatedAt,'2026-09-10T11:13:00.000Z');assert.ok(matchCoversOdds(game,s,now));});
test('stale, wrong matchup, duplicate matchup, and first-five scopes cannot be used',()=>{const s=parseCoversOdds(page(),now);assert.equal(matchCoversOdds(game,s,now+16*60000),null);assert.equal(parseCoversOdds(page(),now+16*60000).status,'stale');assert.equal(matchCoversOdds({...game,away:{id:139}},s,now),null);assert.equal(matchCoversOdds(game,{...s,games:[...s.games,...s.games]},now),null);assert.throws(()=>parseCoversOdds(page().replace('value="1"','value="2"'),now));});
test('wrong totals direction and missing odds are excluded, not guessed',()=>{const s=parseCoversOdds(page().replace('u 6.5','o 6.5'),now);assert.equal(s.games[0].markets.length,2);assert.throws(()=>parseCoversOdds(page().replaceAll('American __american','missing'),now));});

test('percentage-formatted source uses displayed decimal odds without inventing American odds',()=>{const h=page().replaceAll('>-120</span>','>55%</span><span class="Decimal __decimal">1.83</span>').replaceAll('>+100</span>','>50%</span><span class="Decimal __decimal">2.00</span>');const s=parseCoversOdds(h,now);assert.equal(s.games[0].markets.length,3);assert.equal(s.games[0].markets[0].first.american,null);assert.equal(s.games[0].markets[0].first.decimal,1.83);});
