import test from 'node:test';
import assert from 'node:assert/strict';
import {moduleUrl} from './profile-loader.mjs';
const {cpblResults,npbCalendar,kboMonth,profileTeamId,uniqueGames}=await import(moduleUrl('lib/international-profile.ts'));
const {summarize,selectGames}=await import(moduleUrl('lib/team-profile.ts'));
const cp=(year=2026)=>`<tr><td><a href="/box?KindCode=A&amp;Year=${year}&amp;GameSno=341">341</a></td><td>大巨蛋</td><td>${year}/09/19</td><td>02H40M</td><td>味全龍</td><td>3</td><td>中信兄弟</td><td>4</td><td>中信兄弟</td></tr>`;
test('CPBL official home and away results produce correct margins and no duplicate games',()=>{const games=cpblResults(cp()+cp(),2026);assert.equal(games.length,1);const s=summarize(selectGames(games,profileTeamId('CPBL','ACN')),profileTeamId('CPBL','ACN'));assert.equal(s.wins,1);assert.equal(s.runsFor,4);assert.equal(s.winMargin,1);assert.throws(()=>cpblResults(cp(2025),2026));assert.throws(()=>uniqueGames([...games,{...games[0],homeId:5}]));});
test('NPB first team is home; cancellation and future fixtures never count as completed',()=>{const h='Calendar (September 2026)<td class="stschedule"><a href="/bis/eng/2026/games/gm20260919.html">19</a><div><a href="/bis/eng/2026/games/s2026091901440.html">G 14 - 1 D</a></div><div><a href="/bis/eng/2026/games/s2026091901441.html">T * - * C</a></div><div>DB - S 18:00</div></td>';const games=npbCalendar(h,2026);assert.equal(games.length,3);assert.equal(games.find(g=>g.completed).homeId,profileTeamId('NPB','g'));assert.equal(games.filter(g=>g.completed).length,1);assert.equal(games.find(g=>g.status==='未開賽').homeScore,null);assert.equal(new Date(games.find(g=>g.timeKnown).start).getUTCHours(),9);assert.throws(()=>npbCalendar(h,2025));});
test('KBO excludes exhibition games, postponed scores and unplayed zeroes',()=>{const row=(type,score,note='-')=>`<tr><td title="DATE">09.19(SAT)</td><td title="TYPE">${type}</td><td class="TIME">18:30</td><td title="GAME">LG</td><td title="GAME">${score}</td><td title="GAME">DOOSAN</td><td class="LOCATION">JAMSIL</td><td class="ETC">${note}</td></tr>`;const g=kboMonth('<span id="lblGameMonth">2026.09</span>'+row('EXHIBITION','3:1')+row('REGULAR','2:2')+row('REGULAR',':')+row('REGULAR','1:0','POSTPONED'),2026);assert.equal(g.length,3);assert.equal(g.filter(x=>x.completed).length,1);assert.equal(g[1].homeScore,null);const id=profileTeamId('KBO','LG'),s=summarize(selectGames(g,id),id);assert.equal(s.ties,1);assert.equal(s.winRate,null);});

