import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {moduleUrl} from './profile-loader.mjs';
import {parseKboPlayText,parseNpbPlayText,playLabel,enrichGamePlayText,retainGamePlayText} from '../server/baseball-play-text.mjs';
const {internationalTextEvents,internationalTextInnings,selectTextInnings,currentTextPlay}=await import(moduleUrl('lib/international-play-text.ts'));
const time='2026-09-22T13:00:00Z',now=Date.parse(time);
const game=(league='KBO')=>({key:league+':20260922OBWO02026',id:'20260922OBWO02026',league,date:'2026-09-22',status:'final',startTime:'2026-09-22T09:00:00Z',inning:9,half:'bottom',away:{id:'OB',name:'客隊',score:5},home:{id:'WO',name:'主隊',score:3},innings:{away:[{inning:9,runs:0}],home:[{inning:9,runs:0}]},lineups:{away:[],home:[]},starters:{away:null,home:null},source:{url:'https://api-gw.sports.naver.com/schedule/games/20260922OBWO02026/relay?inning=9',fetchedAt:time}});
const state=(out='2',home='3')=>({ball:'3',strike:'2',out,base1:'1',base2:'0',base3:'0',awayScore:'5',homeScore:home,batter:'11'});
function relay(g=game()) {return {gameId:g.id,textRelays:[{no:10,inn:9,homeOrAway:'1',title:'2번타자 타자',textOptions:[{seqno:1,type:8,text:'2번타자 타자',currentGameState:state()},{seqno:2,type:1,text:'1구 헛스윙',pitchNum:1,pitchResult:'S',speed:'135',stuff:'슬라이더',currentGameState:state()},{seqno:3,type:13,text:'타자 : 삼진 아웃',currentGameState:state('3')}]},{no:9,inn:9,homeOrAway:'0',title:'1번타자 타자',textOptions:[{seqno:0,type:13,text:'타자 : 중견수 왼쪽 1루타',currentGameState:state('0')}]}]};}
const parsed=(g=game())=>parseKboPlayText(relay(g),g,g.source,9);
const npb=()=>({...game('NPB'),key:'NPB:123',id:'123',away:{id:'1',name:'巨人'},home:{id:'6',name:'廣島'},source:{url:'https://baseball.yahoo.co.jp/npb/game/123/text',fetchedAt:time}});
const html='<title>2026年9月22日 巨人 広島 一球速報</title><section class="bb-liveText"><h1 class="bb-liveText__inning">試合前情報</h1></section><section class="bb-liveText"><header class="bb-liveText__head bb-liveText__head--npbTeam6"><h1 class="bb-liveText__inning">11回裏</h1></header><ol><li class="bb-liveText__item"><p class="bb-liveText__batter"><span class="bb-liveText__order">8番</span><a href="/npb/player/12345/top">勝田 成</a><span class="bb-liveText__state">一死満塁</span></p><p class="bb-liveText__summary bb-liveText__summary--change">投手交代:中川→赤星</p><p class="bb-liveText__summary bb-liveText__summary--point">ランナーフルベースの2-0から犠飛</p><p class="bb-liveText__summary bb-liveText__summary--point">広島サヨナラ勝ち！ 広 2-1 巨</p><p class="bb-liveText__summary">試合終了</p></li></ol><footer>得点 1X</footer></section>';
test('KBO preserves chronological halves, post-event state, batter identity and actual pitches',()=>{
 const t=parsed();assert.equal(t.records.length,2);assert.deepEqual(t.records.map(r=>r.half),['top','bottom']);const p=t.records[1];assert.equal(p.batter.name,'타자');assert.equal(p.batter.order,2);assert.equal(p.event,'三振出局');assert.equal(p.count.outs,3);assert.equal(p.score.home,3);assert.deepEqual(p.bases,[true,false,false]);assert.equal(p.pitches.length,1);assert.equal(p.pitches[0].speedKph,135);assert.match(p.description,/三振出局/);
});
test('KBO rejects wrong games and never promotes line scores into text',()=>{const g=game();assert.throws(()=>parseKboPlayText({...relay(),gameId:'other'},g,g.source));assert.equal(parseKboPlayText({gameId:g.id,textRelays:[],inningScore:{away:{9:5}}},g,g.source).records.length,0);});
test('KBO reused sequence numbers retain substitutions and batter rows; duplicate blocks collapse',()=>{const g=game(),r=relay();r.textRelays[0].textOptions.unshift({seqno:1,type:2,text:'투수 교체: 투수A',currentGameState:state()});r.textRelays.push(r.textRelays[0]);const p=parseKboPlayText(r,g,g.source,9).records.at(-1);assert.equal(p.batter.name,'타자');assert.equal(p.actions.length,1);assert.equal(p.event,'三振出局');});
test('KBO scoring uses in-event score changes, not the final score on unrelated plays',()=>{const g=game(),r=relay();r.textRelays[0].textOptions.push({seqno:4,type:14,text:'주자 : 홈인',currentGameState:state('3','4')});const t=parseKboPlayText(r,g,g.source,9);assert.equal(t.records.at(-1).scoring,true);assert.equal(t.records[0].scoring,false);});
test('KBO missing states stay unknown and actual zero counts are retained',()=>{const g=game(),r=relay();delete r.textRelays[0].textOptions.at(-1).currentGameState;const t=parseKboPlayText(r,g,g.source,9);assert.equal(t.records.at(-1).count.outs,null);assert.equal(t.records.at(-1).score.home,null);assert.equal(t.records.at(-1).bases,null);assert.equal(t.records[0].count.outs,0);});
test('NPB includes the walk-off bottom half, substitutions and scoring; no invented pitches or after-state',()=>{const g=npb(),t=parseNpbPlayText(html,g,g.source);assert.equal(t.records.length,1);const r=t.records[0];assert.equal(r.inning,11);assert.equal(r.half,'bottom');assert.equal(r.batter.name,'勝田 成');assert.equal(r.event,'高飛犧牲打');assert.equal(r.actions[0].event,'更換投手');assert.equal(r.scoring,true);assert.equal(r.count.outs,null);assert.equal(r.bases,null);assert.equal(r.score.home,null);assert.equal(r.pitches.length,0);});
test('NPB rejects wrong dates, URLs and batting-team assignments',()=>{const g=npb();assert.throws(()=>parseNpbPlayText(html.replace('9月22','9月21'),g,g.source));assert.throws(()=>parseNpbPlayText(html,g,{...g.source,url:g.source.url.replace('/123/','/456/')}));assert.throws(()=>parseNpbPlayText(html.replace('npbTeam6','npbTeam1'),g,g.source));});
test('event classification preserves specific results before generic terms',()=>{for(const [text,name] of [['投手ゴロ エラー','失誤'],['犠牲フライ','高飛犧牲打'],['삼진 아웃','三振出局'],['볼넷','四壞保送'],['不明事件','文字紀錄']])assert.equal(playLabel(text).event,name);});
test('all, latest and numbered filters use text halves even without a linescore entry',()=>{const g=npb();g.playText=parseNpbPlayText(html,g,g.source);const groups=internationalTextInnings(g,now);assert.equal(groups.at(-1).inning,11);assert.equal(groups.at(-1).half,'bottom');assert.equal(selectTextInnings(groups,'latest').length,1);assert.equal(selectTextInnings(groups,'9').length,2);assert.equal(selectTextInnings(groups,'all').length,3);});
test('a CPBL score-only game gets empty event groups rather than manufactured outs or hits',()=>{const g=game('CPBL'),groups=internationalTextInnings(g,now);assert.equal(groups.length,2);assert.ok(groups.every(x=>x.plays.length===0));assert.deepEqual(internationalTextEvents(g,now),[]);});
test('final text survives old capture times but wrong fixtures, teams and future events are excluded',()=>{const g=game();g.playText=parsed(g);assert.equal(internationalTextEvents(g,now+86400000).length,2);for(const change of [t=>t.gameKey='other',t=>t.home='other',t=>t.date='2026-09-21',t=>t.records.forEach(r=>r.fetchedAt='2099-01-01T00:00:00Z')]){const x=structuredClone(g);change(x.playText);assert.equal(internationalTextEvents(x,now).length,0);}});
test('refresh failures preserve exact-fixture text timestamps without rolling back scoreboard values',()=>{const g=game(),old={...g,playText:parsed(g)},fresh={...g,home:{...g.home,score:4},playText:{...parsed(g),status:'unavailable',records:[]}};const result=retainGamePlayText(fresh,old);assert.equal(result.home.score,4);assert.equal(result.playText.records.length,2);assert.equal(result.playText.fetchedAt,time);assert.equal(result.playText.stale,true);assert.equal(retainGamePlayText({...fresh,id:'G2',key:'KBO:G2'},old).playText.records.length,0);});
test('new complete text replaces old records, including source corrections and deletions',()=>{const g=game(),old={...g,playText:parsed(g)},fresh={...g,playText:{...parsed(g),records:parsed(g).records.slice(1)}};assert.equal(retainGamePlayText(fresh,old).playText.records.length,1);});
test('a text-source network error does not fail score collection',async()=>{const g=npb();const result=await enrichGamePlayText(g,{store:new Map(),fetcher:async()=>{throw new Error('offline')}});assert.equal(result.playText.status,'unavailable');assert.deepEqual(result.innings,g.innings);});
test('pregame enrichment never fetches or manufactures events',async()=>{const g={...game(),status:'pregame'};const result=await enrichGamePlayText(g,{fetcher:()=>{throw new Error('must not fetch')}});assert.equal(result,g);assert.deepEqual(internationalTextEvents({...g,playText:parsed()},now),[]);});
test('current pitches require the current batter and never show after a completed game',()=>{const g=game();g.playText=parsed(g);g.currentBatter={id:'11',name:'타자'};assert.equal(currentTextPlay(g,false),null);});

// Execute the actual JSX functions to verify the changed record renderer.
const React={Fragment:'fragment',createElement:(type,props,...children)=>({type,props:props??{},children})};
const nodes=x=>Array.isArray(x)?x.flatMap(nodes):x&&typeof x==='object'?[x,...x.children.flatMap(nodes)]:[];
const text=x=>Array.isArray(x)?x.map(text).join(' '):x&&typeof x==='object'?x.children.map(text).join(' '):typeof x==='string'||typeof x==='number'?String(x):'';
function renderFunction(file,name,scope,args){const source=ts.createSourceFile(file,readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),fn=source.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.ok(fn);const code=ts.transpileModule(fn.getText(source).replace(/^export default /,'').replace(/^export /,''),{compilerOptions:{jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022},fileName:'render.tsx'}).outputText;return new Function(...Object.keys(scope),code+';return '+name)(...Object.values(scope))(args);}
const display=await import(moduleUrl('lib/international-live-display.ts'));
function renderRecords(g,filter='latest',panel='player'){let call=0;const scope={React,useState:()=>[call++===0?panel:filter,()=>{}],UserRound:'person',BaseDiamond:'bases',CountLights:'count',InternationalTeamLogo:'logo',internationalBatter:display.internationalBatter,internationalPosition:display.internationalPosition,internationalTextEvents,internationalTextInnings,selectTextInnings,currentTextPlay,InternationalPlayCard:'play',InternationalTextPitches:'pitches',stat:x=>x??'—'};return renderFunction('app/international-live-records.tsx','InternationalLiveRecords',scope,{game:g,stale:false});}
test('the real records renderer removes score summary cards for all three leagues',()=>{for(const league of ['CPBL','NPB','KBO']){const tree=renderRecords(game(league));assert.match(text(tree),/本半局暫無文字紀錄/);assert.doesNotMatch(text(tree),/本局得分|逐局得分/);assert.ok(nodes(tree).some(n=>n.props['data-play-text-version']));}});
test('the real records renderer routes completed plays and scoring events into narrative cards',()=>{const g=game();g.playText=parsed(g);g.playText.records[1].scoring=true;const tree=renderRecords(g);assert.equal(nodes(tree).filter(n=>n.type==='play').length,2);assert.match(text(tree),/比賽已結束/);const scoring=renderRecords(g,'latest','scoring');assert.equal(nodes(scoring).filter(n=>n.type==='play').length,3);});
test('the actual card renders source actions, batter, outcomes, counts and expandable text',()=>{const g=game(),p=parsed(g).records[1];p.actions=[{id:'action',event:'更換投手',description:'投手A 換上 投手B'}];const tree=renderFunction('app/international-play-card.tsx','InternationalPlayCard',{React,UserRound:'person',BaseDiamond:'bases',CountLights:'count',InternationalTeamLogo:'logo',InternationalTextPitches:'pitches'},{play:p,game:g});assert.match(text(tree),/更換投手/);assert.match(text(tree),/第 2 棒/);assert.match(text(tree),/三振出局/);assert.ok(nodes(tree).some(n=>n.type==='details'));assert.equal(nodes(tree).filter(n=>n.type==='pitches').length,1);assert.equal(nodes(tree).filter(n=>n.type==='count').length,1);});
