import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {moduleUrl} from './profile-loader.mjs';
const {superEntry,superEntryUrl}=await import(moduleUrl('lib/super-entry.ts'));
const {credentialKey,encryptToken}=await import(moduleUrl('lib/tz-credentials.ts'));
const secret=Buffer.alloc(32,4).toString('base64'),key=await credentialKey(secret),ticket='0123456789abcdef0123456789abcdef';
const request=(origin='https://arena.test',extra={})=>new Request('https://arena.test/api/super-entry',{method:'POST',headers:{Origin:origin,'x-super-session':'browser:12345678-1234-1234-1234-123456789abc',...extra}});
async function setup(){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE tz_bindings(member_id TEXT PRIMARY KEY,encrypted_token TEXT,expires_at INTEGER,verified_at INTEGER); CREATE TABLE tz_binding_attempts(member_id TEXT PRIMARY KEY,allowed_at INTEGER,operation_id TEXT)');const db={prepare(q){const s=sql.prepare(q);let args=[];const stmt={bind(...v){args=v;return stmt;},async first(){return s.get(...args)??null;},async run(){return s.run(...args);}};return stmt;}};for(const id of ['a','b'])sql.prepare('INSERT INTO tz_bindings VALUES(?,?,?,?)').run(id,await encryptToken('private-token-'+id,id,key),Date.now()+600000,1);return {db,sql};}
const valid=(url='https://hr9988.net/#/APILogin?MemID='+ticket)=>Response.json({code:200,data:{game_method:'GET',game_url:url,game_post:{}}});
test('each owner receives only their own browser entry without consuming it or exposing TZ token',async()=>{const {db}=await setup(),calls=[];for(const member of ['a','b']){const r=await superEntry(request(),member,db,secret,async(u,o)=>{calls.push(u);assert.equal(u,'https://www.tz6868.com/api/v2/game/SUPER/login');assert.equal(o.headers.Authorization,'Bearer private-token-'+member);assert.equal(o.redirect,'manual');assert.equal(o.cache,'no-store');assert.equal(JSON.parse(o.body).game_device,'Desktop');return valid();});assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/private, no-store/);const d=await r.json();assert.equal(d.url,'https://hr9988.net/#/APILogin?MemID='+ticket);assert.ok(d.reuseUntil>Date.now());assert.equal(JSON.stringify(d).includes('private-token'),false);}assert.equal(calls.length,2);});
test('anonymous, cross-site, unbound and expired requests never contact source',async()=>{const {db,sql}=await setup();const noFetch=()=>{throw Error('Must not contact source');};assert.equal((await superEntry(request(),null,db,secret,noFetch)).status,401);assert.equal((await superEntry(request('https://evil.test'),'a',db,secret,noFetch)).status,403);assert.equal((await superEntry(request('https://arena.test',{'sec-fetch-site':'cross-site'}),'a',db,secret,noFetch)).status,403);assert.equal((await superEntry(request(),'missing',db,secret,noFetch)).status,409);sql.prepare('UPDATE tz_bindings SET expires_at=0 WHERE member_id=?').run('a');assert.equal((await superEntry(request(),'a',db,secret,noFetch)).status,409);});
test('rejects redirected or malicious destinations and malformed tickets',async()=>{for(const u of ['http://hr9988.net/#/APILogin?MemID='+ticket,'https://hr9988.net.evil.test/#/APILogin?MemID='+ticket,'https://evil.test/#/APILogin?MemID='+ticket,'https://user@hr9988.net/#/APILogin?MemID='+ticket,'https://hr9988.net/?redirect=evil#/APILogin?MemID='+ticket,'https://hr9988.net/#/APILogin?MemID=bad','https://hr9988.net/#/APILogin?MemID='+ticket+'&MemID='+ticket])assert.equal(superEntryUrl(u),null);const {db}=await setup();const r=await superEntry(request(),'a',db,secret,async()=>valid('https://evil.test/'));assert.equal(r.status,502);assert.equal((await r.text()).includes('evil.test'),false);});
test('source denial fails closed without replay, member rate limits stay isolated',async()=>{const {db}=await setup();let calls=0;const denied=async()=>{calls++;return new Response('sensitive upstream content',{status:403});};const r=await superEntry(request(),'a',db,secret,denied);assert.equal(r.status,502);assert.equal((await r.text()).includes('sensitive'),false);assert.equal((await superEntry(request(),'a',db,secret,denied)).status,429);assert.equal(calls,1);assert.equal((await superEntry(request(),'b',db,secret,async()=>valid())).status,200);});
test('changed account authorization cannot return an old ticket; mobile entry uses source device flag',async()=>{const {db,sql}=await setup();const r=await superEntry(request('https://arena.test',{'user-agent':'iPhone Mobile'}),'a',db,secret,async(u,o)=>{assert.equal(JSON.parse(o.body).game_device,'Mobile');sql.prepare('UPDATE tz_bindings SET verified_at=2 WHERE member_id=?').run('a');return valid();});assert.equal(r.status,409);assert.equal((await r.text()).includes(ticket),false);});
test('oversized source response is rejected rather than reflected',async()=>{const {db}=await setup();const r=await superEntry(request(),'a',db,secret,async()=>new Response('x'.repeat(70000)));assert.equal(r.status,502);assert.ok((await r.text()).length<300);});
test('mobile entry normalizes a desktop source URL and desktop normalizes a mobile source URL',async()=>{
 for(const [headers,sourceHost,expectedHost,device] of [[{'user-agent':'iPhone Mobile'},'hr9988.net','m.hr9988.net','Mobile'],[{'user-agent':'Macintosh','x-super-device':'mobile'},'hr9988.net','m.hr9988.net','Mobile'],[{'sec-ch-ua-mobile':'?1'},'hr9988.net','m.hr9988.net','Mobile'],[{'user-agent':'Windows NT 10.0'},'m.hr9988.net','hr9988.net','Desktop']]){
  const {db}=await setup();const r=await superEntry(request('https://arena.test',headers),'a',db,secret,async(u,o)=>{assert.equal(JSON.parse(o.body).game_device,device);return valid('https://'+sourceHost+'/#/APILogin?MemID='+ticket);});assert.equal(r.status,200);const url=new URL((await r.json()).url);assert.equal(url.hostname,expectedHost);assert.equal(url.hash,'#/APILogin?MemID='+ticket);
 }
});
