import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {moduleUrl} from './profile-loader.mjs';
const w=await import(moduleUrl('lib/wnba.ts')),a=await import(moduleUrl('lib/wnba-analysis.ts')),nba=await import(moduleUrl('lib/nba.ts')),shared=await import(moduleUrl('lib/nba-analysis.ts')),nav=await import(moduleUrl('lib/sport-navigation.ts')),roster=await import(moduleUrl('lib/wnba-roster.ts'));
const read=name=>JSON.parse(readFileSync(`tests/fixtures/wnba/${name}.json`,'utf8'));
const now=Date.parse('2026-09-29T18:00:00Z'),game=w.parseWnbaEvents(read('day-20260930')).find(g=>g.id==='401918019'),history=['16','20'].flatMap(t=>[2,3].flatMap(p=>w.parseWnbaEvents(read(`team-${t}-2026-${p}`),t)));
test('WNBA has 15 distinct teams, its own route, same-calendar-year seasons and expansion start dates',()=>{assert.equal(w.WNBA_TEAMS.length,15);assert.equal(new Set(w.WNBA_TEAMS.map(t=>t.id)).size,15);assert.equal(w.wnbaSeason('2026-09-30'),2026);assert.equal(w.wnbaSeason('2026-01-01'),2026);assert.equal(w.wnbaFirstSeason('131935'),2026);assert.equal(nav.frontSelection('?league=WNBA').league,'WNBA');assert.equal(nav.leaguePageHref('WNBA'),'/?league=WNBA&view=analysis');for(const t of w.WNBA_TEAMS){assert.match(nba.basketballTeamHref(t),/^\/teams\/wnba\//);assert.match(t.logo,/teamlogos\/wnba\//);}});
test('WNBA parser rejects NBA league/team feeds and preserves playoff phases and Taiwan dates',()=>{assert.equal(w.wnbaDay(game.start),'2026-10-01');assert.equal(game.phase,3);assert.equal(game.home.name,'華盛頓神秘人');assert.throws(()=>w.parseWnbaEvents(JSON.parse(readFileSync('tests/fixtures/nba/future.json'))));const wrong=read('team-16-2026-2');wrong.team.abbreviation='MIN';assert.throws(()=>w.parseWnbaEvents(wrong,'16'));const wrongEvent=read('day-20260930');wrongEvent.events[0].uid='s:40~l:46~e:401918019';assert.ok(!w.parseWnbaEvents(wrongEvent).some(g=>g.id===game.id));});
test('analysis uses WNBA scoring and recommends exactly the higher unrounded win probability',()=>{const r=a.analyzeWnba(game,history,now);assert.equal(r.status,'ready');assert.equal(r.model,'wnba-recent-results-v1');assert.equal(r.homeForm.games,20);assert.equal(r.awayForm.games,20);assert.ok(r.expected.total>100&&r.expected.total<220);assert.equal(r.probabilities.home+r.probabilities.away,1);const pick=shared.nbaPick(game,r);assert.equal(pick.probability,Math.max(r.probabilities.home,r.probabilities.away));assert.ok(shared.readyNbaAnalysis(game,{game,analysis:r,sourceFetchedAt:new Date(now).toISOString()},now));assert.equal(shared.readyNbaAnalysis(game,{game,analysis:{...r,model:'nba-recent-results-v1'},sourceFetchedAt:new Date(now).toISOString()},now),null);});
test('started/stale fixtures, small samples, and NBA-only history cannot create a WNBA recommendation',()=>{const r=a.analyzeWnba(game,history,now),report={game,analysis:r,sourceFetchedAt:new Date(now).toISOString()};assert.equal(a.analyzeWnba(game,[],now).status,'waiting');assert.equal(a.analyzeWnba({...game,home:{...game.home,league:'NBA'}},history,now).status,'waiting');assert.equal(a.analyzeWnba(game,history.map(g=>({...g,home:{...g.home,league:'NBA'},away:{...g.away,league:'NBA'}})),now).status,'waiting');assert.equal(shared.readyNbaAnalysis({...game,state:'live'},report,now),null);assert.equal(shared.readyNbaAnalysis(game,report,now+11*60000),null);});
test('WNBA roster retains real names and separate WNBA photo/stat URLs; NBA athletes rejected',()=>{const raw=read('roster-16'),r=roster.parseWnbaRoster(raw,'16');assert.equal(r.roster.length,14);assert.equal(r.rosterSeason,'2026');for(const p of r.roster){assert.match(p.photo,/headshots\/wnba\//);assert.match(p.href,/espn.com\/wnba\/player\/stats\//);}raw.athletes[0].uid='s:40~l:46~a:1';assert.throws(()=>roster.parseWnbaRoster(raw,'16'));});
let serial=0;
async function setup(run,fail=false){const RealDate=Date,native=fetch,paths=[];globalThis.Date=class extends RealDate{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};globalThis.fetch=async input=>{const u=new URL(input);paths.push(u.href);assert.ok(u.pathname.includes('/basketball/wnba/'));if(u.pathname.endsWith('/summary'))return Response.json(JSON.parse(readFileSync('tests/fixtures/basketball-efficiency/wnba-boxes.json','utf8'))[u.searchParams.get('event')]);const team=u.pathname.match(/teams\/(\d+)\/schedule/);if(team){if(fail&&u.searchParams.get('seasontype')==='3')return new Response('',{status:503});return Response.json(read(`team-${team[1]}-${u.searchParams.get('season')}-${u.searchParams.get('seasontype')}`));}return Response.json(read(`day-${u.searchParams.get('dates')}`));};try{await run(await import(moduleUrl('lib/wnba-source.ts')+'#'+serial++),paths);}finally{globalThis.Date=RealDate;globalThis.fetch=native;}}
test('source keeps WNBA history cached and withholds player forecasts when official availability is missing',async()=>setup(async(s,paths)=>{const r=await s.wnbaGameAnalysis('2026-10-01',game.id);assert.equal(r.analysis.status,'waiting');assert.equal(r.analysis.playerContext.reason,'official_roster_or_availability_unavailable');assert.equal(r.analysis.probabilities,undefined);const espnRequests=()=>paths.filter(p=>p.includes('/basketball/wnba/')).length,count=espnRequests();await s.wnbaGameAnalysis('2026-10-01',game.id);assert.equal(espnRequests(),count);assert.ok(!paths.some(p=>p.includes('season=2027')));const profile=await s.wnbaTeamProfile('16');assert.ok(profile.results.length>=44);assert.equal(profile.upcoming[0].phase,3);const season=await s.wnbaTeamSeasonProfile('16',2026,2);assert.equal(season.games.length,44);assert.equal((await s.wnbaTeamSeasonProfile('131935',2025,2)).games.length,0);}));
test('missing WNBA postseason history fails closed instead of publishing partial recommendations',async()=>setup(async s=>{await assert.rejects(s.wnbaGameAnalysis('2026-10-01',game.id));},true));
