'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ChartContainer} from '@/components/ui/chart';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {ChevronLeft,ChevronRight,RefreshCw} from 'lucide-react';
import {selectGames,summarize} from '@/lib/team-profile';
import {profileTeams,profileTeamId,profileHref,type ProfileLeague,type ProfileGame} from '@/lib/international-profile';
import InternationalTeamLogo from './international-team-logo';
function PlayerPhoto({src,alternatives,league,name,team}:{src?:string;alternatives?:string[];league:ProfileLeague;name:string;team:string}){
 const urls=useMemo(()=>[...new Set([...(alternatives||[]),src].filter((u):u is string=>Boolean(u)))],[src,alternatives]);
 const [index,setIndex]=useState(0);useEffect(()=>setIndex(0),[src,alternatives]);
 return <span className="international-player-photo">{urls[index]?<img key={urls[index]} src={urls[index]} alt={`${name} 球員照片`} width={84} height={98} loading="lazy" onError={()=>setIndex(i=>i+1)}/>:<InternationalTeamLogo league={league} name={team} size={64}/>}</span>;
}
const fmt=(v:unknown,d=2)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';
const percent=(v:unknown)=>typeof v==='number'?`${(v*100).toFixed(1)}%`:'—';
function useProfile(query:string|null){
 const [state,setState]=useState<{key:string;data:any;error:string}>({key:'',data:null,error:''}),[revision,setRevision]=useState(0),[loading,setLoading]=useState(Boolean(query));
 useEffect(()=>{if(!query)return;const c=new AbortController();let active=true;setLoading(true);const timer=setTimeout(()=>c.abort(),110000);
  fetch('/api/international-team?'+query,{signal:c.signal,cache:'no-store'}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'讀取失敗');if(active)setState({key:query,data,error:''});}).catch(()=>{if(active)setState(old=>({key:query,data:old.key===query?old.data:null,error:'資料讀取失敗，請按更新重試。'}));}).finally(()=>{clearTimeout(timer);if(active)setLoading(false);});return()=>{active=false;clearTimeout(timer);c.abort();};
 },[query,revision]);useEffect(()=>{if(!query)return;const timer=setInterval(()=>setRevision(v=>v+1),300000);return()=>clearInterval(timer);},[query]);
 return {data:state.key===query?state.data:null,error:state.key===query?state.error:'',loading,refresh:()=>setRevision(v=>v+1)};
}
function choose(label:string,value:string,onChange:(v:string)=>void,options:string[][]){return <label className="team-filter"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>;}
function leagueStats(games:ProfileGame[],league:ProfileLeague,venue:string,limit:number){let count=0,w=0,l=0,rf=0,ra=0;for(const code of Object.keys(profileTeams[league])){const s=summarize(selectGames(games,profileTeamId(league,code),venue,limit),profileTeamId(league,code));count+=s.games;w+=s.wins;l+=s.losses;rf+=(s.runsFor||0)*s.games;ra+=(s.runsAgainst||0)*s.games;}return {winRate:w+l?w/(w+l):null,runsFor:count?rf/count:null,runsAgainst:count?ra/count:null};}
export default function InternationalTeamProfile({league,code,season,initialMonth}:{league:ProfileLeague;code:string;season:number;initialMonth:number}){
 const current=season;
 const id=profileTeamId(league,code),name=profileTeams[league][code],codes=Object.keys(profileTeams[league]);
 const [view,setView]=useState('overview'),[venue,setVenue]=useState('all'),[limit,setLimit]=useState('0'),[metric,setMetric]=useState('winRate'),[month,setMonth]=useState(initialMonth),[calendar,setCalendar]=useState('calendar'),[kind,setKind]=useState('bat'),[search,setSearch]=useState('');
 const query=`league=${league}&team=${code}`,profile=useProfile(query),players=useProfile(view==='players'?query+'&action=players':null),upcoming=useProfile(view==='games'&&league==='CPBL'?query+'&action=upcoming':null);
 const data=profile.data,allGames:ProfileGame[]=data?.games||[];
 const selected=useMemo(()=>selectGames(allGames,id,venue,+limit),[data,id,venue,limit]),stats=useMemo(()=>summarize(selected,id),[selected,id]),average=useMemo(()=>leagueStats(allGames,league,venue,+limit),[data,league,venue,limit]);
 const h2h=codes.filter(c=>c!==code).map(c=>({code:c,...summarize(selected.filter(g=>[g.homeId,g.awayId].includes(profileTeamId(league,c))),id)})).filter(s=>s.games).sort((a,b)=>b.games-a.games);
 const trend=Array.from({length:12},(_,i)=>{const own=selected.filter(g=>+g.date.slice(5,7)===i+1),leagueGames=allGames.filter(g=>+g.date.slice(5,7)===i+1);return {month:`${i+1} 月`,own:own.length?(summarize(own,id) as any)[metric]:null,average:own.length?(leagueStats(leagueGames,league,venue,0) as any)[metric]:null};});
 const teamName=(teamId:number)=>profileTeams[league][codes[teamId-1]]||'未知球隊';
 const combined=new Map<number,ProfileGame>((upcoming.data?.games||[]).map((g:ProfileGame)=>[g.id,g]));for(const g of allGames)combined.set(g.id,g);
 const scoped=[...combined.values()].filter((g:ProfileGame)=>[g.homeId,g.awayId].includes(id)&&(venue==='all'||venue==='home'&&g.homeId===id||venue==='away'&&g.awayId===id));
 const calendarGames=scoped.filter(g=>+g.date.slice(5,7)===month).sort((a,b)=>a.start.localeCompare(b.start)||a.id-b.id),table=players.data?.[kind],playerRows=(table?.rows||[]).filter((r:string[])=>!search||r[0]?.toLowerCase().includes(search.toLowerCase()));
 const gameEntry=(g:ProfileGame)=>{const home=g.homeId===id,op=home?g.awayId:g.homeId,own=home?g.homeScore:g.awayScore,against=home?g.awayScore:g.homeScore;return <div className="calendar-game"><span>{home?'主':'客'} · <InternationalTeamLogo league={league} name={teamName(op)} size={20}/>{teamName(op)}</span><strong>{g.completed?`${own!>against!?'勝':own!<against!?'敗':'和'} ${own}：${against}`:g.status}</strong>{!g.completed&&g.homeScore!==null&&g.awayScore!==null&&<small>目前 {own}：{against}</small>}{g.timeKnown&&!g.completed&&<small>{new Date(g.start).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false})}</small>}{g.venue&&<small>{g.venue}</small>}</div>;};
 function refresh(){profile.refresh();if(view==='players')players.refresh();if(view==='games')upcoming.refresh();}
 const sources=[...(data?.sources||[]),...(view==='players'?players.data?.sources||[]:[]),...(view==='games'?upcoming.data?.sources||[]:[])];
 return <main className="arena-shell min-h-screen international-team-profile"><header className="team-page-nav"><Link href={`/?league=${league}&view=analysis`}>← 賽前分析・串關</Link><Link href={`/?league=${league}&view=teams`}>球隊一覽</Link></header><div className="team-page-container">
 <div className="team-identity"><InternationalTeamLogo league={league} name={name} size={64}/><div><p className="league-eyebrow">{league} / 球隊資料</p><h1>{name}</h1></div><Button variant="outline" onClick={refresh} disabled={profile.loading||view==='players'&&players.loading}><RefreshCw className={profile.loading?'animate-spin':''}/>更新</Button></div>
 <Tabs value={view} onValueChange={setView}><TabsList className="league-tabs" aria-label="球隊資料分類">{[['overview','概覽'],['trends','月度趨勢'],['games','近期賽事'],['players','球員']].map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList><TabsContent value={view}>
 <div className="team-filters panel">{choose('年度',String(current),()=>{},[[String(current),String(current)]])}{choose('賽事類型','R',()=>{},[['R','例行賽']])}{view==='players'?<>{choose('球員成績',kind,setKind,[['bat','打者'],['pit','投手']])}<label className="team-filter"><span>搜尋球員</span><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="輸入球員姓名"/></label></>:<>{choose('主客場',venue,setVenue,[['all','全部'],['home','主場'],['away','客場']])}{choose('場數',limit,setLimit,[['0','全季'],['5','近 5 場'],['10','近 10 場'],['20','近 20 場']])}</>}</div>
 {profile.error&&<div className="panel p-4 my-4" role="alert">{profile.error}</div>}
 {view!=='players'&&(!data?<div className="panel p-6 my-6" role="status">{profile.loading?'正在整理官方逐場紀錄…':'尚未取得球隊資料，請按更新重試。'}</div>:<>
 {(data.warnings?.length>0||data.status==='stale')&&<div className="panel p-4 mt-4 text-amber-200" role="status">{data.status==='stale'?'顯示上次成功取得的紀錄。 ':''}{data.warnings.join('；')}。以下依已取得的 {stats.games} 場完賽紀錄計算。</div>}
 {view!=='games'&&<div className="team-metrics">{[['戰績',`${stats.wins}－${stats.losses}${stats.ties?'－'+stats.ties:''}`,`${stats.games} 場`],['勝率',percent(stats.winRate),stats.streak],['場均得分',fmt(stats.runsFor),`失分 ${fmt(stats.runsAgainst)}`],['得失分差',fmt(stats.runDiff),'每場'],['平均勝分差',fmt(stats.winMargin),`${stats.wins} 勝`],['平均敗分差',fmt(stats.lossMargin),`${stats.losses} 敗`]].map(([k,v,n])=><div key={k}><span>{k}</span><strong>{v}</strong><small>{n}</small></div>)}</div>}
 {view==='overview'&&<div className="team-detail-grid"><section className="panel p-5"><h2 className="team-section-title">團隊數據比較</h2>{[['勝率',stats.winRate,average.winRate],['場均得分',stats.runsFor,average.runsFor],['場均失分',stats.runsAgainst,average.runsAgainst]].map(([label,a,b])=><div className="team-comparison" key={String(label)}><div><b>{label==='勝率'?percent(a):fmt(a)}</b><span>{label}</span><b>{label==='勝率'?percent(b):fmt(b)}</b></div><div className="comparison-bars" aria-hidden="true">{typeof a==='number'&&typeof b==='number'&&a+b>0?<><span style={{width:`${a/(a+b)*100}%`}}/><span style={{width:`${b/(a+b)*100}%`}}/></>:<span style={{width:'100%',background:'#263447'}}/>}</div><div><small className="flex items-center gap-2"><InternationalTeamLogo league={league} name={name} size={20}/>{name}</small><small>{league} 平均</small></div></div>)}<p className="team-footnote">依同一聯盟、主客場與場數範圍計算；勝率不計和局。更新來源可能有延遲。</p><Button variant="outline" onClick={()=>setView('players')}>查看完整投打成績 →</Button></section><section className="panel p-5"><h2 className="team-section-title">對各隊戰績</h2>{h2h.length?h2h.map(r=><div className="team-opponent" key={r.code}><div><Link href={profileHref(league,r.code)} className="flex items-center gap-2"><InternationalTeamLogo league={league} name={profileTeams[league][r.code]} size={24}/>{profileTeams[league][r.code]}</Link><span>{r.games} 場</span></div><small>勝 {r.wins} · 敗 {r.losses}{r.ties?` · 和 ${r.ties}`:''}</small><div className="opponent-bar" aria-label={`${r.wins}勝${r.losses}敗${r.ties}和`}><span style={{width:`${r.wins/r.games*100}%`,background:'#199568'}}/><span style={{width:`${r.losses/r.games*100}%`,background:'#d95668'}}/>{r.ties>0&&<span style={{width:`${r.ties/r.games*100}%`,background:'#8290a3'}}/>}</div></div>):<p>此範圍尚無已完賽紀錄。</p>}</section></div>}
 {view==='trends'&&<section className="panel p-5"><h2 className="team-section-title">月度趨勢</h2><div className="flex flex-wrap gap-2 mb-5">{[['winRate','勝率'],['runsFor','場均得分'],['runsAgainst','場均失分']].map(([k,t])=><Button key={k} variant={metric===k?'default':'outline'} aria-pressed={metric===k} onClick={()=>setMetric(k)}>{t}</Button>)}</div>{selected.length?<ChartContainer config={{own:{label:name,color:'#ffd538'},average:{label:`${league} 當月平均`,color:'#94a3b8'}}} className="h-[340px] w-full aspect-auto"><LineChart data={trend} margin={{left:4,right:12,top:12,bottom:4}} accessibilityLayer><CartesianGrid vertical={false} stroke="#263447"/><XAxis dataKey="month" tick={{fontSize:12}}/><YAxis width={54} domain={metric==='winRate'?[0,1]:['auto','auto']} tickFormatter={v=>metric==='winRate'?percent(v):fmt(v,1)}/><Tooltip contentStyle={{background:'#101b2a',borderColor:'#344158',color:'#fff'}} formatter={(v:any)=>metric==='winRate'?percent(v):fmt(v)}/><Legend/><Line dataKey="own" name={name} stroke="#ffd538" strokeWidth={3} connectNulls={false}/><Line dataKey="average" name={`${league} 當月平均`} stroke="#94a3b8" strokeDasharray="4 4" connectNulls={false}/></LineChart></ChartContainer>:<p>此範圍尚無已完賽紀錄。</p>}<p className="team-footnote">月份依來源賽事日期；聯盟線為同主客場條件的當月全部完賽紀錄，空白月份不補值。</p></section>}
 {view==='games'&&<section className="panel p-5 mt-6"><div className="team-calendar-heading"><h2 className="team-section-title">近期賽事</h2><div className="flex items-center gap-2"><Button variant="ghost" disabled={month===1} onClick={()=>setMonth(m=>m-1)} aria-label="上一個月"><ChevronLeft/></Button><b>{current} 年 {month} 月</b><Button variant="ghost" disabled={month===12} onClick={()=>setMonth(m=>m+1)} aria-label="下一個月"><ChevronRight/></Button><Button variant={calendar==='calendar'?'default':'outline'} onClick={()=>setCalendar('calendar')}>月曆</Button><Button variant={calendar==='list'?'default':'outline'} onClick={()=>setCalendar('list')}>列表</Button></div></div>{calendar==='calendar'?<div className="team-calendar-scroll"><div className="team-calendar">{['日','一','二','三','四','五','六'].map(d=><div className="calendar-weekday" key={d}>{d}</div>)}{Array.from({length:new Date(current,month-1,1).getDay()},(_,i)=><div className="calendar-empty" key={`empty-${i}`}/>)}{Array.from({length:new Date(current,month,0).getDate()},(_,i)=><div key={i} className="calendar-day"><b>{i+1}</b>{calendarGames.filter(g=>+g.date.slice(8,10)===i+1).map(g=><div key={g.id}>{gameEntry(g)}</div>)}</div>)}</div></div>:<div className="team-game-list">{(limit==='0'?calendarGames:calendarGames.filter(g=>g.completed&&selected.some(s=>s.id===g.id))).map(g=><div key={g.id}><span>{g.date.slice(5)}</span>{gameEntry(g)}</div>)}</div>}{!calendarGames.length&&<p className="team-footnote">本月未取得符合條件的賽程。</p>}<p className="team-footnote">比分順序：本隊：對手。時間為台灣時間；月曆顯示當月完整賽程，場數篩選套用於完賽列表。{league==='CPBL'&&(upcoming.loading?' 待賽資訊讀取中…':upcoming.error?' 待賽資訊暫缺；已完賽紀錄仍可查看。':'')}</p></section>}
 </>)}
 {view==='players'&&<section className="panel p-5 mt-6"><h2 className="team-section-title">球員名單</h2>{players.data?.warnings?.length>0&&<p role="status" className="text-amber-200 mb-4">{players.data.warnings.join('；')}</p>}{players.loading&&!players.data?<p role="status">正在取得球員資料…</p>:players.error?<p role="alert">{players.error}</p>:!table?<p>此類球員資料暫未取得。</p>:<><p className="team-footnote mb-4">{current} · {kind==='bat'?'打者':'投手'} · {playerRows.length} 人；點球員卡查看完整球季成績</p><div className="team-player-grid">{playerRows.map((row:string[],i:number)=><details className="team-player-card international-player-card" key={`${row[0]}-${i}`}><summary><PlayerPhoto src={players.data?.photos?.[row[0]]} alternatives={players.data?.photoAlternatives?.[row[0]]} league={league} name={row[0]} team={name}/><h3>{row[0]}</h3><p>{kind==='bat'?'打者':'投手'}</p></summary><div className="international-player-stats">{table.headers.slice(1).map((header:string,j:number)=><div key={header}><span>{header}</span><strong>{row[j+1]||'—'}</strong></div>)}</div></details>)}</div>{!playerRows.length&&<p>沒有符合搜尋條件的球員。</p>}</>}</section>}
 <footer className="team-footnote mt-6"><p>資料範圍：{current} 一軍例行賽。擷取：{(view==='players'?players.data:data)?.fetchedAt?new Date((view==='players'?players.data:data).fetchedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'讀取中'}（台灣）</p><p className="flex flex-wrap gap-x-4 gap-y-1 mt-2">{sources.filter((s:any)=>s.label!=='KBO 官方逐月例行賽紀錄').map((s:any)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="underline">{s.label} ↗</a>)}</p></footer>
 </TabsContent></Tabs></div></main>;
}
