'use client';
import {useEffect,useState} from 'react';
import {basketballTeamHref,nbaDay,nbaForm,nbaPhase,nbaSeason,nbaTeam,nbaTeamHref,type NbaGame} from '@/lib/nba';
import {playerHref,playerPhoto,positionZh,profileGroups,profileResults,seasonLabel} from '@/lib/nba-profile';
import {wnbaTeam,wnbaTeamHref,wnbaSeason} from '@/lib/wnba';
import type {OfficialTeam} from '@/lib/nba-official';
import type {NbaTeamProfileData} from '@/lib/nba-source';
import {nbaRequest} from './nba-request';
import {NbaTeamIdentity,nbaTime} from './nba-match';
import './nba.css';
export default function NbaTeamProfile({id,returnDay,league='NBA'}:{league?:'NBA'|'WNBA';id:string;returnDay?:string}){
 const team=(league==='WNBA'?wnbaTeam:nbaTeam)(id)!,[data,setData]=useState<NbaTeamProfileData|null>(null),[official,setOfficial]=useState<OfficialTeam|null>(null),[officialError,setOfficialError]=useState(''),[error,setError]=useState(''),[revision,setRevision]=useState(0),[limit,setLimit]=useState(0),[venue,setVenue]=useState('all'),[tab,setTab]=useState('overview'),[season,setSeason]=useState<number|null>(null),[phase,setPhase]=useState(2),[games,setGames]=useState<NbaGame[]|null>(null),[seasonError,setSeasonError]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');nbaRequest(`/api/${league.toLowerCase()}?kind=team&team=${id}`,c.signal).then(d=>{if(!c.signal.aborted){setData(d);setSeason(s=>s??d.results[0]?.season??(league==='WNBA'?wnbaSeason(nbaDay()):nbaSeason(nbaDay())));}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setSeason(s=>s??(league==='WNBA'?wnbaSeason(nbaDay()):nbaSeason(nbaDay())));}});return()=>c.abort();},[id,revision,league]);
 useEffect(()=>{const c=new AbortController();setOfficial(null);setOfficialError('');nbaRequest(`/api/${league.toLowerCase()}?kind=team-official&team=${id}`,c.signal).then(d=>{if(!c.signal.aborted)setOfficial(d);}).catch(()=>{if(!c.signal.aborted)setOfficialError('官方球員資料暫時無法載入');});return()=>c.abort();},[id,revision,league]);
 useEffect(()=>{if(!season)return;const c=new AbortController();setGames(null);setSeasonError('');nbaRequest(`/api/${league.toLowerCase()}?kind=team-season&team=${id}&season=${season}&phase=${phase}`,c.signal).then(d=>{if(!c.signal.aborted)setGames(d.games);}).catch(e=>{if(!c.signal.aborted)setSeasonError(e.message);});return()=>c.abort();},[id,season,phase,revision,league]);
 const labelSeason=league==='WNBA'?(year:number)=>String(year):seasonLabel,teamHref=league==='WNBA'?wnbaTeamHref:nbaTeamHref,currentSeason=league==='WNBA'?wnbaSeason(nbaDay()):nbaSeason(nbaDay());
 const results=profileResults(games||[],id,season||0,phase,venue,limit),form=nbaForm(results,id,results.length),opponents=profileGroups(results,id,'opponent'),months=profileGroups(results,id,'month');
 const retry=<button type="button" onClick={()=>setRevision(n=>n+1)}>重新載入</button>;
 return <main className="arena-shell nba-profile" data-sport="basketball"><div className="nba-profile-inner"><a className="nba-back" href={`/?league=${league}&view=analysis${returnDay?`&date=${returnDay}`:''}`}>← 返回 {league} 分析</a><div className="nba-profile-heading"><NbaTeamIdentity team={team}/><div><span className="nba-eyebrow">{league} 球隊數據</span><h1>{team.name}</h1><p>{team.code}{official&&league==='NBA'?` · ${official.background.conference==='East'?'東區':'西區'} · ${official.background.arena}`:''}</p></div></div>
  <nav className="nba-profile-tabs" aria-label="球隊數據分頁">{[['overview','概覽'],['monthly','月度趨勢'],['games','近期賽事'],['players','球員']].map(([v,label])=><button type="button" key={v} aria-pressed={tab===v} onClick={()=>setTab(v)}>{label}</button>)}</nav>
  {tab==='players'?<section className="nba-profile-panel"><div className="nba-panel-title"><h2>球員名單</h2><span>{official?.rosterSeason?`${labelSeason(Number(official.rosterSeason)+(league==='NBA'?1:0))} · ${official.roster.length} 位球員`:''}</span></div>{officialError?<p role="alert">{officialError} {retry}</p>:!official?<p className="nba-empty">正在取得球員名單…</p>:<div className="nba-roster">{official.roster.map(p=><a className="nba-player-card" data-league={league} key={p.id} href={league==='WNBA'?(p.href||`https://www.espn.com/wnba/player/stats/_/id/${p.id}`):playerHref(p.id)} target={league==='WNBA'?'_blank':undefined} rel={league==='WNBA'?'noreferrer':undefined}><img key={p.photo||p.id} src={p.photo||(league==='WNBA'?`https://a.espncdn.com/i/headshots/wnba/players/full/${p.id}.png`:playerPhoto(p.id))} srcSet={p.photo?.endsWith('-cutout.png')?`/_next/image?url=${encodeURIComponent(p.photo)}&w=256&q=75 1x, /_next/image?url=${encodeURIComponent(p.photo)}&w=640&q=75 2x`:undefined} alt={p.name} loading="lazy" onError={e=>{const img=e.currentTarget;if(p.photoFallback&&img.dataset.fallback!=='1'){img.dataset.fallback='1';img.removeAttribute('srcset');img.src=p.photoFallback;}else img.style.visibility='hidden';}}/><div><small>{p.number?`#${p.number} · `:''}{positionZh(p.position)}</small><strong>{p.name}</strong><span>{p.height||'—'}{p.weight?` · ${p.weight} 磅`:''}</span>{<>{p.country&&<span>{p.country}</span>}{p.school&&<span>{p.school}</span>}{p.draftYear&&<span>{p.draftYear==='Undrafted'?'未經選秀':`${p.draftYear} 年選秀`}</span>}{p.supplementalStats&&<span>{p.supplementalStats.league} {p.supplementalStats.season} 場均：{p.supplementalStats.points??'—'} 分・{p.supplementalStats.rebounds??'—'} 籃板・{p.supplementalStats.assists??'—'} 助攻</span>}{p.averages&&<span>{p.averages.season} 場均：{p.averages.points??'—'} 分・{p.averages.rebounds??'—'} 籃板・{p.averages.assists??'—'} 助攻</span>}</>}<b>查看球員數據 ↗</b></div></a>)}</div>}</section>:<>
  <div className="nba-profile-selects"><label>球季<select aria-label="球季" value={season||''} onChange={e=>setSeason(Number(e.target.value))}><option value="" disabled>載入中</option>{Array.from({length:10},(_,i)=>currentSeason-i).map(y=><option key={y} value={y}>{labelSeason(y)}</option>)}</select></label><label>賽事<select aria-label="賽事" value={phase} onChange={e=>setPhase(Number(e.target.value))}>{[2,3,1].map(p=><option key={p} value={p}>{nbaPhase(p)}</option>)}</select></label><label>場地<select aria-label="場地" value={venue} onChange={e=>setVenue(e.target.value)}><option value="all">全部</option><option value="home">主場</option><option value="away">客場</option></select></label><label>場次<select aria-label="場次" value={limit} onChange={e=>setLimit(Number(e.target.value))}>{[[0,'整季'],[5,'近 5 場'],[10,'近 10 場'],[20,'近 20 場']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></div>
  {seasonError?<p className="nba-alert" role="alert">{seasonError} {retry}</p>:games===null?<p className="nba-empty" role="status">正在取得球季數據…</p>:<>
  <div className="nba-profile-stats nba-profile-summary"><div><span>戰績</span><strong>{form.wins} 勝 {form.losses} 負</strong><small>{form.games} 場{nbaPhase(phase)}</small></div><div><span>勝率</span><strong>{form.games?`${(form.wins/form.games*100).toFixed(1)}%`:'—'}</strong></div><div><span>場均得分</span><strong>{form.pointsFor===null?'—':Math.round(form.pointsFor)}</strong></div><div><span>場均失分</span><strong>{form.pointsAgainst===null?'—':Math.round(form.pointsAgainst)}</strong></div><div><span>場均淨勝分</span><strong>{form.net===null?'—':`${Math.round(form.net)>0?'+':''}${Math.round(form.net)}`}</strong></div></div>
  {tab==='overview'?<div className="nba-profile-columns"><section className="nba-profile-panel"><div className="nba-panel-title"><h2>對各隊戰績</h2><span>{season?labelSeason(season):''} · {nbaPhase(phase)}</span></div>{opponents.length?opponents.map(r=><div className="nba-opponent" key={r.key}><a href={teamHref(r.key)}><img src={r.logo} alt=""/><strong>{r.name}</strong></a><span>{r.wins} 勝 {r.losses} 負</span><b>{(r.wins/r.games*100).toFixed(1)}%</b><div className="nba-win-bar" aria-label={`對${r.name}勝率 ${(r.wins/r.games*100).toFixed(1)}%`}><i style={{width:`${r.wins/r.games*100}%`}}/></div></div>):<p className="nba-empty">此範圍尚無對戰紀錄</p>}</section><TeamFacts official={official} league={league} season={season} phase={phase} venue={venue} limit={limit} results={results} id={id} onPlayers={()=>setTab('players')}/></div>:tab==='monthly'?<section className="nba-profile-panel"><h2>月度戰績</h2><div className="nba-table-scroll"><table className="nba-data-table"><thead><tr>{['月份','場次','勝','負','勝率','場均得分','場均失分','淨勝分'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{months.map(r=><tr key={r.key}><th>{r.name}</th><td>{r.games}</td><td>{r.wins}</td><td>{r.losses}</td><td>{(r.wins/r.games*100).toFixed(1)}%</td><td>{Math.round(r.points/r.games)}</td><td>{Math.round(r.against/r.games)}</td><td>{Math.round((r.points-r.against)/r.games)}</td></tr>)}</tbody></table></div>{!months.length&&<p className="nba-empty">此範圍尚無賽果</p>}</section>:<div className="nba-profile-columns"><section className="nba-profile-panel"><h2>賽事紀錄</h2>{results.map(g=><ProfileMatch key={g.id} game={g} teamId={id}/>)}{!results.length&&<p className="nba-empty">此範圍尚無賽果</p>}</section><section className="nba-profile-panel"><h2>接下來的賽程</h2>{data?.upcoming.map(g=><ProfileMatch key={g.id} game={g} teamId={id} upcoming/>)}{error?<p role="alert">{error} {retry}</p>:!data?.upcoming.length&&<p className="nba-empty">{data?'尚無後續賽程':'正在取得賽程…'}</p>}</section></div>}
  </>}
  </>}
 </div></main>;
}
function ProfileMatch({game:g,teamId,upcoming=false}:{game:NbaGame;teamId:string;upcoming?:boolean}){
 const home=g.home.id===teamId,opponent=home?g.away:g.home,own=home?g.homeScore:g.awayScore,against=home?g.awayScore:g.homeScore,win=own!>against!;
 return <article className="nba-profile-game"><div><time dateTime={g.start}>{g.timeConfirmed?nbaTime(g.start):`${nbaDay(g.start)}・時間待定`}</time><span>{nbaPhase(g.phase)}</span></div><div><small>{g.neutral?'中立':home?'主場':'客場'}</small><a href={basketballTeamHref(opponent)}>{opponent.name}</a>{upcoming?<b>VS</b>:<><b>{own} : {against}</b><span className="nba-result" data-result={win?'W':'L'}>{win?'勝':'負'}</span></>}</div></article>;
}

export function TeamFacts({official,league,season,phase,venue,limit,results,id,onPlayers}:{official:OfficialTeam|null;league:'NBA'|'WNBA';season:number|null;phase:number;venue:string;limit:number;results:NbaGame[];id:string;onPlayers:()=>void}){
 const label=season?(league==='NBA'?seasonLabel(season):String(season)):'—';
 const form=nbaForm(results,id,results.length);
 // Official team pages expose their current season, not the selected archive.
 // Their aggregate ranks apply only to an unfiltered regular season with games.
 const sameSeason=!!official&&official.team.id===id&&official.season.replace('–','-')===label.replace('–','-');
 const fullOfficial=sameSeason&&league==='NBA'&&phase===2&&venue==='all'&&limit===0&&form.games>0&&Number(official?.record.wins)+Number(official?.record.losses)>0;
 return <section className="nba-profile-panel" data-testid="team-facts"><h2>球隊資訊</h2>
  <p className="nba-profile-caption">{label} · {nbaPhase(phase)} · {venue==='home'?'主場':venue==='away'?'客場':'全部場地'} · {limit?`近 ${limit} 場`:'整季'}</p>
  <dl className="nba-facts">
   <dt>統計場次</dt><dd>{form.games} 場</dd>
   {results.length>0&&<><dt>比賽日期</dt><dd>{nbaDay(results[results.length-1].start)} ～ {nbaDay(results[0].start)}</dd></>}
   {fullOfficial&&official?.record.conferenceRank!=null&&<><dt>東西區排名</dt><dd>{official.record.conferenceRank}</dd></>}
   <dt>場均得分</dt><dd>{form.pointsFor===null?'—':Math.round(form.pointsFor)}</dd>
   <dt>場均失分</dt><dd>{form.pointsAgainst===null?'—':Math.round(form.pointsAgainst)}</dd>
   {fullOfficial&&official?.ranks.rebounds!=null&&<><dt>場均籃板</dt><dd>{official.ranks.rebounds}</dd></>}
   {fullOfficial&&official?.ranks.assists!=null&&<><dt>場均助攻</dt><dd>{official.ranks.assists}</dd></>}
  </dl>
  {official&&<><p className="nba-profile-caption">目前球隊資料</p><dl className="nba-facts">
   <dt>現任主教練</dt><dd>{official.background.coach||'—'}</dd>
   {league==='NBA'&&<><dt>主場</dt><dd>{official.background.arena||'—'}</dd><dt>創隊年份</dt><dd>{official.background.founded??'—'}</dd><dt>歷年總冠軍</dt><dd>{official.championships.length} 次</dd></>}
   {league==='WNBA'&&<><dt>目前球員人數</dt><dd>{official.roster.length}</dd></>}
  </dl><button className="nba-source-link" type="button" onClick={onPlayers}>查看球員名單 ↗</button></>}
 </section>;
}
