'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {ChartContainer} from '@/components/ui/chart';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {ChevronLeft,ChevronRight,RefreshCw} from 'lucide-react';
import {selectGames,summarize,type TeamGame} from '@/lib/team-profile';
import {teamZh,gameDetailZh} from './zh';
const current=new Date().getUTCFullYear(),types=[['R','例行賽'],['S','春訓熱身賽'],['F','外卡系列賽'],['D','分區系列賽'],['L','聯盟冠軍賽'],['W','世界大賽']],years=Array.from({length:current-2021+1},(_,i)=>String(current-i));
const metrics:Record<string,string>={winRate:'勝率',runsFor:'場均得分',runsAgainst:'場均失分',avg:'打擊率 AVG',obp:'上壘率 OBP',ops:'OPS'};
function useTeamData(query:string|null){const [state,setState]=useState<{key:string;data:any;error:string}>({key:'',data:null,error:''}),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false);useEffect(()=>{if(!query)return;const c=new AbortController();let active=true;let timer:ReturnType<typeof setTimeout>;async function run(){setLoading(true);try{timer=setTimeout(()=>c.abort(),110000);const r=await fetch('/api/team?'+query,{signal:c.signal,cache:'no-store'}),data=await r.json();if(!r.ok)throw Error();setState({key:query!,data,error:''});}catch{if(active)setState({key:query!,data:null,error:c.signal.aborted?'讀取逾時，請重試。':'資料暫時無法取得，請重試。'});}finally{clearTimeout(timer);if(active)setLoading(false);}}void run();return()=>{active=false;clearTimeout(timer);c.abort();};},[query,revision]);useEffect(()=>{if(!query)return;const t=setInterval(()=>setRevision(v=>v+1),5*60000);return()=>clearInterval(t);},[query]);return {data:state.key===query?state.data:null,error:state.key===query?state.error:'',loading,refresh:()=>setRevision(v=>v+1)};}
function fmt(v:any,digits=2){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(digits):'—';}
function percent(v:any){return typeof v==='number'?`${(v*100).toFixed(1)}%`:'—';}
const name=(id:number)=>teamZh({id});
function choose(label:string,value:string,onChange:(v:string)=>void,options:string[][]){return <label className="team-filter"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>;}
function leagueSummary(games:TeamGame[],venue:string,limit:number){const ids=[...new Set(games.flatMap(g=>[g.homeId,g.awayId]))];let n=0,w=0,l=0,rf=0,ra=0;for(const id of ids){const s=summarize(selectGames(games,id,venue,limit),id);n+=s.games;w+=s.wins;l+=s.losses;rf+=(s.runsFor||0)*s.games;ra+=(s.runsAgainst||0)*s.games;}return {winRate:w+l?w/(w+l):null,runsFor:n?rf/n:null,runsAgainst:n?ra/n:null};}
export default function TeamProfile({id}:{id:number}){
 const [season,setSeason]=useState(String(current)),[type,setType]=useState('R'),[venue,setVenue]=useState('all'),[limit,setLimit]=useState('0'),[view,setView]=useState('overview'),[metric,setMetric]=useState('winRate');
 const [calendar,setCalendar]=useState('calendar'),[month,setMonth]=useState(new Date().getUTCMonth()+1),[calendarYear,setCalendarYear]=useState(current),[rosterMode,setRosterMode]=useState('active'),[position,setPosition]=useState('all'),[search,setSearch]=useState('');
 const profile=useTeamData(`id=${id}&season=${season}&type=${type}`),history=useTeamData(view==='trends'&&season!=='all'?`id=${id}&season=${season}&type=${type}&action=history`:null),roster=useTeamData(view==='players'?`id=${id}&season=${season==='all'?current:season}&type=${type}&action=roster&roster=${rosterMode}`:null);
 const data=profile.data,allGames:TeamGame[]=data?.games||[];
 const selected=useMemo(()=>selectGames(allGames,id,venue,Number(limit)),[data,id,venue,limit]),stats=useMemo(()=>summarize(selected,id),[selected,id]);
 const league=useMemo(()=>leagueSummary(data?.leagueGames||[],venue,Number(limit)),[data,venue,limit]);
 const h2h=useMemo(()=>{const ids=[...new Set(selected.map(g=>g.homeId===id?g.awayId:g.homeId))];return ids.map(op=>({id:op,...summarize(selected.filter(g=>[g.homeId,g.awayId].includes(op)),id)})).sort((a,b)=>b.games-a.games||a.id-b.id);},[selected,id]);
 const prior=useMemo(()=>(history.data?.seasons||[]).flatMap((p:any)=>selectGames(p.games,id,venue,Number(limit))),[history.data,id,venue,limit]);
 const [monthBench,setMonthBench]=useState<{key:string;values:Record<number,any>}>({key:'',values:{}}),benchKey=`${season}:${type}`;
 const months=useMemo(()=>[...new Set(selected.map(g=>Number(g.date.slice(5,7))))].sort((a,b)=>a-b),[selected]);
 useEffect(()=>{if(view!=='trends'||!['avg','obp','ops'].includes(metric)||season==='all')return;const c=new AbortController(),values:Record<number,any>={};let next=0;const queue=[...months];setMonthBench({key:benchKey,values:{}});void Promise.all([0,1].map(async()=>{while(next<queue.length&&!c.signal.aborted){const m=queue[next++];try{const r=await fetch(`/api/team?id=${id}&season=${season}&type=${type}&action=league-month&month=${m}`,{signal:c.signal});if(r.ok){const d=await r.json();if(d.teams>0)values[m]=d;}}catch{}if(!c.signal.aborted)setMonthBench({key:benchKey,values:{...values}});}}));return()=>c.abort();},[view,metric,season,type,months.join(','),id]);
 const trend=Array.from({length:12},(_,i)=>{const m=i+1,own=selected.filter(g=>+g.date.slice(5,7)===m),previous=prior.filter((g:TeamGame)=>+g.date.slice(5,7)===m),ls=(data?.leagueGames||[]).filter((g:TeamGame)=>+g.date.slice(5,7)===m);const bm=['avg','obp','ops'].includes(metric)?(monthBench.key===benchKey?monthBench.values[m]:null):leagueSummary(ls,'all',0);return {month:`${m} 月`,selected:own.length?(summarize(own,id) as any)[metric]:null,previous:previous.length?(summarize(previous,id) as any)[metric]:null,league:own.length?bm?.[metric]??null:null};});
 const scopedGames=allGames.filter(g=>venue==='all'||venue==='home'&&g.homeId===id||venue==='away'&&g.awayId===id),calendarGames=scopedGames.filter(g=>new Date(g.start).toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}).startsWith(`${calendarYear}-${String(month).padStart(2,'0')}`));
 function moveMonth(delta:number){const d=new Date(Date.UTC(calendarYear,month-1+delta,1)),y=d.getUTCFullYear();if(y<2021||y>current)return;setMonth(d.getUTCMonth()+1);setCalendarYear(y);if(season!=='all'&&String(y)!==season)setSeason(String(y));}
 const playerGroups:Record<string,string>={P:'投手',C:'捕手','1B':'一壘手','2B':'二壘手','3B':'三壘手',SS:'游擊手',LF:'左外野手',CF:'中外野手',RF:'右外野手',OF:'外野手',DH:'指定打擊',TWP:'投打二刀流'};
 const players=(roster.data?.players||[]).filter((p:any)=>(position==='all'||position==='P'&&['P','TWP'].includes(p.position)||position==='other'&&p.position!=='P')&&p.name.toLowerCase().includes(search.toLowerCase()));
 return <main className="arena-shell min-h-screen"><header className="team-page-nav"><Link href="/">← 賽前分析・串關</Link><Link href="/teams">球隊一覽</Link></header><div className="team-page-container"><div className="team-identity"><img src={`https://www.mlbstatic.com/team-logos/${id}.svg`} width={64} height={64} alt=""/><div><p className="league-eyebrow">MLB / 球隊資料</p><h1>{name(id)}</h1></div><Button variant="outline" onClick={profile.refresh} disabled={profile.loading}><RefreshCw className={profile.loading?'animate-spin':''}/>更新</Button></div>
 <Tabs value={view} onValueChange={setView}><TabsList className="league-tabs" aria-label="球隊資料分類"><TabsTrigger value="overview">概覽</TabsTrigger><TabsTrigger value="trends">月度趨勢</TabsTrigger><TabsTrigger value="games">近期賽事</TabsTrigger><TabsTrigger value="players">球員</TabsTrigger></TabsList><TabsContent value={view}>
 <div className="team-filters panel">{choose('年度',season,v=>{setSeason(v);if(Number(v)<current)setRosterMode('fullSeason');setCalendarYear(v==='all'?current:+v);setMonth(v===String(current)?new Date().getUTCMonth()+1:4);},[['all',`全部（2021～${current}）`],...years.map(y=>[y,y])])}{view!=='players'&&<>{choose('賽事類型',type,setType,types)}{choose('主客場',venue,setVenue,[['all','全部'],['home','主場'],['away','客場']])}{view!=='games'&&choose('場數',limit,setLimit,[['0','全季'],['5','近 5 場'],['10','近 10 場'],['20','近 20 場']])}</>}</div>
 {view!=='players'&&(profile.error?<div className="panel p-5" role="alert">{profile.error}<Button variant="ghost" onClick={profile.refresh}>重試</Button></div>:!data?<div className="panel p-6" role="status">正在整理球隊資料…</div>:<>
 {view!=='games'&&<div className="team-metrics">{[['戰績',`${stats.wins}－${stats.losses}${stats.ties?'－'+stats.ties:''}`,`${stats.games} 場`],['勝率',percent(stats.winRate),stats.streak],['場均得分',fmt(stats.runsFor),`失分 ${fmt(stats.runsAgainst)}`],['得失分差',fmt(stats.runDiff),'每場'],['平均勝分差',fmt(stats.winMargin),`${stats.wins} 勝`],['平均敗分差',fmt(stats.lossMargin),`${stats.losses} 敗`]].map(([k,v,n])=><div key={k}><span>{k}</span><strong>{v}</strong><small>{n}</small></div>)}</div>}
 {view==='overview'&&<><div className="team-detail-grid"><section className="panel p-5"><h2 className="team-section-title">團隊數據比較</h2>{[['勝率',stats.winRate,league.winRate],['場均得分',stats.runsFor,league.runsFor],['場均失分',stats.runsAgainst,league.runsAgainst],['OPS',stats.ops,venue==='all'&&limit==='0'?data.leagueHitting?.ops:null],['團隊防禦率',stats.era,venue==='all'&&limit==='0'?data.leaguePitching?.era:null],['WHIP',stats.whip,venue==='all'&&limit==='0'?data.leaguePitching?.whip:null]].map(([label,a,b])=><div className="team-comparison" key={String(label)}><div><b>{label==='勝率'?percent(a):fmt(a,label==='OPS'?3:2)}</b><span>{label}</span><b>{label==='勝率'?percent(b):fmt(b,label==='OPS'?3:2)}</b></div><div className="comparison-bars" aria-hidden="true">{typeof a==='number'&&typeof b==='number'&&a+b>0?<><span style={{width:`${a/(a+b)*100}%`}}/><span style={{width:`${b/(a+b)*100}%`}}/></>:<span style={{width:'100%',background:'#263447'}}/>}</div><div><small>{name(id)}</small><small>MLB 平均</small></div></div>)}<p className="team-footnote">{venue!=='all'||limit!=='0'?'篩選後的 OPS、防禦率及 WHIP 聯盟對照暫缺。':'聯盟比率按累計打席、打數與出局數加權。'} 投打資料涵蓋 {stats.hittingGames}／{stats.pitchingGames} 場。</p></section><section className="panel p-5"><h2 className="team-section-title">對各隊戰績</h2>{h2h.length?h2h.map(r=><div className="team-opponent" key={r.id}><div><Link href={`/teams/${r.id}`}>{name(r.id)}</Link><span>{r.games} 場</span></div><small>勝 {r.wins} · 敗 {r.losses}{r.ties?` · 和 ${r.ties}`:''}</small><div className="opponent-bar" aria-label={`${r.wins}勝${r.losses}敗`}><span style={{width:`${r.wins/r.games*100}%`,background:'#199568'}}/><span style={{width:`${r.losses/r.games*100}%`,background:'#d95668'}}/>{r.ties>0&&<span style={{width:`${r.ties/r.games*100}%`,background:'#8290a3'}}/>}</div></div>):<p>這個範圍沒有已完賽紀錄。</p>}</section></div></>}
 {view==='trends'&&<section className="panel p-5"><h2 className="team-section-title">月度趨勢</h2><div className="flex flex-wrap gap-2 mb-5" role="group" aria-label="趨勢指標">{Object.entries(metrics).map(([k,t])=><Button key={k} variant={metric===k?'default':'outline'} onClick={()=>setMetric(k)} aria-pressed={metric===k}>{t}</Button>)}</div>{!selected.length?<p>此範圍沒有可繪製的完場紀錄。</p>:<ChartContainer config={{selected:{label:'選擇賽季',color:'#ffd538'},previous:{label:'前兩年合併',color:'#38bdf8'},league:{label:'聯盟當月平均（不分主客）',color:'#94a3b8'}}} className="h-[340px] w-full aspect-auto"><LineChart data={trend} margin={{left:4,right:12,top:12,bottom:4}} accessibilityLayer><CartesianGrid vertical={false} stroke="#263447"/><XAxis dataKey="month" tick={{fontSize:12}}/><YAxis width={54} domain={metric==='winRate'?[0,1]:['auto','auto']} tickFormatter={v=>metric==='winRate'?`${Math.round(v*100)}%`:fmt(v,metric==='avg'||metric==='obp'||metric==='ops'?3:1)}/><Tooltip contentStyle={{background:'#101b2a',borderColor:'#344158',color:'#fff'}} formatter={(v:any)=>metric==='winRate'?percent(v):fmt(v,3)}/><Legend/><Line dataKey="selected" name="選擇賽季" stroke="#ffd538" strokeWidth={3} connectNulls={false} dot={{r:4}}/>{season!=='all'&&<Line dataKey="previous" name="前兩年合併" stroke="#38bdf8" strokeDasharray="7 5" connectNulls={false}/>}<Line dataKey="league" name="聯盟當月平均（不分主客）" stroke="#94a3b8" strokeDasharray="2 5" connectNulls={false} dot={false}/></LineChart></ChartContainer>}<p className="team-footnote">月份依 MLB 官方賽事日期。未完成月份不補值；前兩年按場次與打席合併。{history.loading?' 歷史比較讀取中…':history.error?' 歷史比較暫時無法取得。':''}{season==='all'?' 合併年度的 AVG／OBP／OPS 聯盟月平均暫缺。':''}</p></section>}
 {view==='games'&&<section className="panel p-5"><div className="team-calendar-heading"><h2 className="team-section-title">近期賽事</h2><div className="flex items-center gap-2"><Button variant="ghost" onClick={()=>moveMonth(-1)} aria-label="上一個月"><ChevronLeft/></Button><b>{calendarYear} 年 {month} 月</b><Button variant="ghost" onClick={()=>moveMonth(1)} aria-label="下一個月"><ChevronRight/></Button><Button variant={calendar==='calendar'?'default':'outline'} onClick={()=>setCalendar('calendar')}>月曆</Button><Button variant={calendar==='list'?'default':'outline'} onClick={()=>setCalendar('list')}>列表</Button></div></div>{calendar==='calendar'?<div className="team-calendar-scroll"><div className="team-calendar">{['日','一','二','三','四','五','六'].map(d=><div className="calendar-weekday" key={d}>{d}</div>)}{Array.from({length:new Date(Date.UTC(calendarYear,month-1,1)).getUTCDay()},(_,i)=><div className="calendar-empty" key={`empty-${i}`}/>)}{Array.from({length:new Date(Date.UTC(calendarYear,month,0)).getUTCDate()},(_,i)=>{const day=i+1,date=`${calendarYear}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,games=calendarGames.filter(g=>new Date(g.start).toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'})===date);return <div key={day} className={`calendar-day ${date===new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'})?'calendar-today':''}`}><b>{day}</b>{games.map(g=><GameEntry key={g.id} g={g} id={id}/>)}</div>;})}</div></div>:<div className="team-game-list">{calendarGames.map(g=><div key={g.id}><span>{new Date(g.start).toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit'})}</span><GameEntry g={g} id={id}/></div>)}</div>}{!calendarGames.length&&<p className="team-footnote">本月沒有符合條件的賽事。</p>}<p className="team-footnote">日期與開賽時間皆為台灣時間。雙重賽分開顯示。</p></section>}
 <p className="team-footnote">更新：{new Date(data.fetchedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}（台灣）</p></>)}
 {view==='players'&&<section className="panel p-5"><div className="team-filters">{choose('名單',rosterMode,setRosterMode,Number(season)<current?[['fullSeason','球季名單']]:[['active','目前大聯盟名單'],['fullSeason','球季名單']])}{choose('守備類別',position,setPosition,[['all','全部'],['P','投手'],['other','野手／其他']])}<label className="team-filter"><span>搜尋球員</span><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="輸入球員原文姓名"/></label></div><p className="team-footnote">{roster.data?.season||season} · {roster.data?.mode==='active'?'目前名單':'球季名單（包含球季內異動）'} · {players.length} 人</p>{roster.loading&&!roster.data?<p role="status">正在取得球員名單…</p>:roster.error?<p role="alert">{roster.error}<Button variant="ghost" onClick={roster.refresh}>重試</Button></p>:<div className="team-player-grid">{players.map((p:any)=><article className="team-player-card" key={p.id}><img src={`https://img.mlbstatic.com/mlb-photos/image/upload/w_120,q_auto:best/v1/people/${p.id}/headshot/67/current`} width={80} height={80} loading="lazy" alt="" onError={e=>{e.currentTarget.style.visibility='hidden';}}/><h3>{p.name}</h3><p>#{p.number||'—'} · {playerGroups[p.position]||'其他'}</p></article>)}</div>}<p className="team-footnote">歷史年度顯示球季名單；照片為來源目前頭像。</p></section>}
 </TabsContent></Tabs></div></main>;
}
function GameEntry({g,id}:{g:TeamGame;id:number}){const home=g.homeId===id,opponent=home?g.awayId:g.homeId;return <div className="calendar-game"><span>{home?'主':'客'} · {name(opponent)}</span><strong>{g.completed?`${g.awayScore}：${g.homeScore}`:g.state==='Preview'?gameDetailZh({status:{detailedState:g.status},gameDate:g.start}):g.state==='Live'?'進行中':gameDetailZh({status:{detailedState:g.status},gameDate:g.start})}</strong>{g.completed&&<small>客：主</small>}</div>;}
