export type TeamGame={id:number;season:number;date:string;start:string;homeId:number;awayId:number;homeScore:number|null;awayScore:number|null;state:string;status:string;completed:boolean;hitting?:any;pitching?:any};
const finite=(v:any)=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
export function normalizeSchedule(raw:any,season:number,type:string):TeamGame[]{
 const seen=new Map<number,TeamGame>();for(const d of raw?.dates||[])for(const g of d.games||[]){if(g.gameType!==type||g.season&&Number(g.season)!==season)continue;const scored=finite(g.teams?.home?.score)&&finite(g.teams?.away?.score);seen.set(g.gamePk,{id:g.gamePk,season,date:g.officialDate||d.date,start:g.resumeDate||g.gameDate,homeId:g.teams.home.team.id,awayId:g.teams.away.team.id,homeScore:scored?Number(g.teams.home.score):null,awayScore:scored?Number(g.teams.away.score):null,state:g.status?.abstractGameState||'Preview',status:g.status?.detailedState||'',completed:g.status?.abstractGameState==='Final'&&scored&&!['Cancelled','Postponed','Suspended'].includes(g.status?.detailedState)});}
 return [...seen.values()].sort((a,b)=>Date.parse(a.start)-Date.parse(b.start)||a.id-b.id);
}
export function logMap(raw:any,teamId:number,season:number){
 const out=new Map<number,any>();for(const group of raw?.stats||[]){const kind=group.group?.displayName;if(!['hitting','pitching'].includes(kind))continue;for(const s of group.splits||[]){if(s.team?.id!==teamId||Number(s.season)!==season||!s.game?.gamePk)continue;const row=out.get(s.game.gamePk)||{id:s.game.gamePk,date:s.date,isHome:s.isHome,opponentId:s.opponent?.id};row[kind]=s.stat;out.set(s.game.gamePk,row);}}
 return out;
}
export function attachLogs(games:TeamGame[],raw:any,teamId:number,season:number){const logs=logMap(raw,teamId,season);return games.filter(g=>[g.homeId,g.awayId].includes(teamId)).map(g=>{const l=logs.get(g.id),score=g.homeId===teamId?g.homeScore:g.awayScore,against=g.homeId===teamId?g.awayScore:g.homeScore;return {...g,hitting:l?.hitting&&Number(l.hitting.runs)===score?l.hitting:undefined,pitching:l?.pitching&&Number(l.pitching.runs)===against?l.pitching:undefined};});}
export function historyFromLogs(raw:any,teamId:number,season:number):TeamGame[]{return [...logMap(raw,teamId,season).values()].filter(r=>r.hitting&&r.pitching&&finite(r.hitting.runs)&&finite(r.pitching.runs)).map(r=>({id:r.id,season,date:r.date,start:r.date+'T12:00:00Z',homeId:r.isHome?teamId:r.opponentId,awayId:r.isHome?r.opponentId:teamId,homeScore:Number(r.isHome?r.hitting.runs:r.pitching.runs),awayScore:Number(r.isHome?r.pitching.runs:r.hitting.runs),state:'Final',status:'Final',completed:true,hitting:r.hitting,pitching:r.pitching})).sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);}
export function selectGames(games:TeamGame[],teamId:number,venue='all',limit=0){const all=games.filter(g=>g.completed&&[g.homeId,g.awayId].includes(teamId)&&(venue==='all'||venue==='home'&&g.homeId===teamId||venue==='away'&&g.awayId===teamId)).sort((a,b)=>Date.parse(a.start)-Date.parse(b.start)||a.id-b.id);return limit?all.slice(-limit):all;}
const ratio=(n:number|null,d:number|null)=>n!==null&&d!==null&&d>0?n/d:null;
export function aggregateStats(stats:any[],kind:'hitting'|'pitching'){
 const sum=(k:string)=>stats.length&&stats.every(s=>finite(s?.[k]))?stats.reduce((n,s)=>n+Number(s[k]),0):null;
 if(kind==='hitting'){const h=sum('hits'),ab=sum('atBats'),bb=sum('baseOnBalls'),hp=sum('hitByPitch'),sf=sum('sacFlies'),tb=sum('totalBases');const avg=ratio(h,ab),obp=h!==null&&bb!==null&&hp!==null&&ab!==null&&sf!==null?ratio(h+bb+hp,ab+bb+hp+sf):null,slg=ratio(tb,ab);return {avg,obp,ops:obp!==null&&slg!==null?obp+slg:null,era:null,whip:null};}
 const outs=sum('outs'),er=sum('earnedRuns'),bb=sum('baseOnBalls'),h=sum('hits');return {avg:null,obp:null,ops:null,era:er!==null?ratio(er*27,outs):null,whip:h!==null&&bb!==null?ratio((h+bb)*3,outs):null};
}
export function summarize(games:TeamGame[],teamId:number){
 let wins=0,losses=0,ties=0,scored=0,allowed=0,winMargin=0,lossMargin=0;for(const g of games){const a=(g.homeId===teamId?g.homeScore:g.awayScore)!,b=(g.homeId===teamId?g.awayScore:g.homeScore)!;scored+=a;allowed+=b;if(a>b){wins++;winMargin+=a-b;}else if(a<b){losses++;lossMargin+=b-a;}else ties++;}
 const h=aggregateStats(games.map(g=>g.hitting),'hitting'),p=aggregateStats(games.map(g=>g.pitching),'pitching');let streak=0,last='';for(const g of [...games].reverse()){const a=(g.homeId===teamId?g.homeScore:g.awayScore)!,b=(g.homeId===teamId?g.awayScore:g.homeScore)!,r=a>b?'勝':a<b?'敗':'和';if(last&&last!==r)break;last=r;streak++;}
 return {games:games.length,wins,losses,ties,winRate:ratio(wins,wins+losses),runsFor:ratio(scored,games.length),runsAgainst:ratio(allowed,games.length),runDiff:ratio(scored-allowed,games.length),winMargin:ratio(winMargin,wins),lossMargin:ratio(lossMargin,losses),avg:h.avg,obp:h.obp,ops:h.ops,era:p.era,whip:p.whip,streak:streak?`${streak} 連${last}`:'—',hittingGames:games.filter(g=>g.hitting).length,pitchingGames:games.filter(g=>g.pitching).length};
}
export function leagueStats(raw:any,groupName:'hitting'|'pitching'){const group=raw?.stats?.find((g:any)=>g.group?.displayName===groupName),splits=group?.splits||[];const seen=new Set();const rows=splits.filter((s:any)=>{if(seen.has(s.team?.id))return false;seen.add(s.team?.id);return true;});return {teams:rows.length,...aggregateStats(rows.map((r:any)=>r.stat),groupName)};}
