'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import TurnstileWidget from './turnstile-widget';
import './cover.css';
import {Input} from '@/components/ui/input';
export default function Login(){const [required,setRequired]=useState<boolean|null>(null);const [siteKey,setSiteKey]=useState('');const [turnstileToken,setTurnstileToken]=useState(''),[attempt,setAttempt]=useState(0);const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState('驗證中…');
 useEffect(()=>{const reason=new URLSearchParams(window.location.search).get('reason');if(reason==='tz-expired')setError('授權已失效，請重新輸入帳密取得新授權。');fetch('/api/session').then(r=>r.json()).then(d=>{if(typeof d.turnstileRequired==='boolean')setRequired(d.turnstileRequired);if(typeof d.turnstileSiteKey==='string')setSiteKey(d.turnstileSiteKey);if(d.signedIn)setUsername(current=>current||d.username);}).catch(()=>{});},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||required===null||(required&&!turnstileToken))return;setBusy(true);setPhase('驗證中…');setError('');const body=JSON.stringify({username:username.trim(),password,turnstileToken});setPassword('');try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body,signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'登入失敗');setPhase('登入中…');if(d.source==='ofa'){window.location.assign('/admin');return;}
 const connected=await fetch('/api/hr9988',{method:'POST',signal:AbortSignal.timeout(55000)});const connection=await connected.json();if(connected.status===401||connection.code==='tz_auth_expired')throw new Error(connection.error||'授權未生效，請重新驗證');window.location.assign('/');}catch(e){setError(e instanceof Error?e.message:'連線失敗');setBusy(false);setTurnstileToken('');setAttempt(n=>n+1);}}
 return <main className="yj-login min-h-screen flex items-center justify-center p-5 text-slate-100"><video className="yj-login-video" autoPlay muted loop playsInline preload="metadata" poster="/backgrounds/yankee-stadium.jpg" aria-hidden="true"><source src="/0912-bg.mp4" type="video/mp4"/></video><div className="yj-login-shade" aria-hidden="true"/><section className="panel relative z-10 w-full max-w-md p-8 space-y-6"><div className="flex gap-3 items-center"><img src="/yj-logo.png" width={48} height={48} alt="YJ"/><h1 className="text-2xl font-bold">YJ體育分析</h1></div><p className="text-slate-300">使用帳號登入。</p><form onSubmit={submit} className="space-y-4"><label className="block">帳號<Input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required maxLength={128} disabled={busy}/></label><label className="block">密碼<Input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={256} disabled={busy}/></label>{required&&<TurnstileWidget siteKey={siteKey} onToken={setTurnstileToken} attempt={attempt}/>} {required===null&&<p>正在讀取登入設定，若久未完成請重新整理。</p>}{error&&<p role="alert" className="text-amber-300">{error}</p>}<Button type="submit" className="w-full" disabled={busy||required===null||(required&&!turnstileToken)}>{busy?phase:'登入'}</Button></form><div className="flex flex-wrap items-center gap-3"><p className="text-sm text-slate-400">網站不保存密碼。</p><Button asChild variant="destructive" className="h-9 shrink-0 bg-red-600 px-4 text-sm font-bold text-white hover:bg-red-700"><a href="https://line.me/ti/p/ZuZetvA6NY" target="_blank" rel="noopener noreferrer" aria-label="聯繫作者，開啟 LINE（另開視窗）">聯繫作者</a></Button></div></section></main>;
}
